name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ["self-hosted", "mac-mini", "mac", "macos"]
    steps:
      - uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.10"

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create venv and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Run lints
        run: ./scripts/lint.sh

  test:
    name: test
    runs-on: ["self-hosted", "mac-mini", "mac", "macos"]
    env:
      RUNNER_TOOL_CACHE: "${{ github.workspace }}/.github/toolcache"

    steps:
      - uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.10"

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Setup
        run: ./scripts/setup.sh

      - name: Run tests
        run: ./scripts/test.sh -u
