name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: 0.35.0
          RYE_INSTALL_OPTION: "--yes"

      - name: Install dependencies
        run: rye sync --all-features

      - name: Run lints
        run: ./scripts/lint.sh
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: 0.35.0
          RYE_INSTALL_OPTION: "--yes"

      - name: Setup
        run: ./scripts/setup.sh

      - name: Run tests
        run: ./scripts/test.sh -u
